/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import javax.swing.JTable;
import java.lang.String;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Byron Garcia
 */
public class VentanaPrincipalAdministradores extends javax.swing.JFrame {

    /**
     * Creates new form VentaPrincipalAdministradores
     */
    public VentanaPrincipalAdministradores() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    NuevasInsercionesUsuario nuevaInsercion = new NuevasInsercionesUsuario();
    Metodos metodo = new Metodos();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreUsuarioLogged = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        butonVerUsuarios = new javax.swing.JButton();
        botonVerGrupos = new javax.swing.JButton();
        botonAgregarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentanaAdministradores = new javax.swing.JTable();
        botonBitacoraUsuario = new javax.swing.JButton();
        botonBitacoraProyecto = new javax.swing.JButton();
        botonVerAdministradores = new javax.swing.JButton();
        botonVerDirectores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Ventana de administrador");

        butonVerUsuarios.setBackground(new java.awt.Color(0, 153, 153));
        butonVerUsuarios.setText("Ver Usuarios");
        butonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonVerUsuariosActionPerformed(evt);
            }
        });

        botonVerGrupos.setBackground(new java.awt.Color(0, 153, 153));
        botonVerGrupos.setText("Ver Grupos");
        botonVerGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerGruposActionPerformed(evt);
            }
        });

        botonAgregarUsuario.setBackground(new java.awt.Color(0, 153, 153));
        botonAgregarUsuario.setText("Agregar Usuario");
        botonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUsuarioActionPerformed(evt);
            }
        });

        tablaVentanaAdministradores.setBackground(new java.awt.Color(0, 204, 204));
        tablaVentanaAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    tablaVentanaAdministradores.setEnabled(false);
    jScrollPane1.setViewportView(tablaVentanaAdministradores);

    botonBitacoraUsuario.setBackground(new java.awt.Color(0, 153, 153));
    botonBitacoraUsuario.setText("Ver Bitácora Usuarios");
    botonBitacoraUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonBitacoraUsuarioActionPerformed(evt);
        }
    });

    botonBitacoraProyecto.setBackground(new java.awt.Color(0, 153, 153));
    botonBitacoraProyecto.setText("Ver Bitácora Proyectos");
    botonBitacoraProyecto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonBitacoraProyectoActionPerformed(evt);
        }
    });

    botonVerAdministradores.setBackground(new java.awt.Color(0, 153, 153));
    botonVerAdministradores.setText("Ver Administradores");
    botonVerAdministradores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonVerAdministradoresActionPerformed(evt);
        }
    });

    botonVerDirectores.setBackground(new java.awt.Color(0, 153, 153));
    botonVerDirectores.setText("Ver Directores");
    botonVerDirectores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonVerDirectoresActionPerformed(evt);
        }
    });

    jLabel1.setText("Usuario:");

    botonEliminarUsuario.setBackground(new java.awt.Color(0, 153, 153));
    botonEliminarUsuario.setText("Eliminar Usuario");
    botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonEliminarUsuarioActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(106, 106, 106)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(botonVerAdministradores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(botonVerGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerDirectores))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(botonBitacoraUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(botonBitacoraProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 56, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(labelNombreUsuarioLogged, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombreUsuarioLogged, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(butonVerUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBitacoraProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBitacoraUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerGrupos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerDirectores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerAdministradores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(24, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonVerUsuariosActionPerformed
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaUsuariosCompleta());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonVerUsuariosActionPerformed

    private void botonVerGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerGruposActionPerformed
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaGrupos());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerGruposActionPerformed

    private void botonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUsuarioActionPerformed
        VentanaAgregarUsuario ventanaAgregarUsuario = new VentanaAgregarUsuario(this, true);
        ventanaAgregarUsuario.setLocationRelativeTo(null);
        ventanaAgregarUsuario.setVisible(true);
    }//GEN-LAST:event_botonAgregarUsuarioActionPerformed

    private void botonBitacoraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBitacoraUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaBitacoraUsuarios());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonBitacoraUsuarioActionPerformed

    private void botonBitacoraProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBitacoraProyectoActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaBitacoraProyectos());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonBitacoraProyectoActionPerformed

    private void botonVerAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerAdministradoresActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaAdministradores());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonVerAdministradoresActionPerformed

    private void botonVerDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDirectoresActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaAdministradores.setModel(metodo.GeneracionTablaDirectores());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerDirectoresActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        VentanaEliminarUsuario ventanaEliminarUsuario = new VentanaEliminarUsuario(this, true);
 
        try {
            nuevaInsercion.ComboBoxSetValueNombresUsuarios(ventanaEliminarUsuario.comboBoxIdUsuario);
            ventanaEliminarUsuario.setVisible(true);
            ventanaEliminarUsuario.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaAgregarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarUsuario;
    private javax.swing.JButton botonBitacoraProyecto;
    private javax.swing.JButton botonBitacoraUsuario;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonVerAdministradores;
    private javax.swing.JButton botonVerDirectores;
    private javax.swing.JButton botonVerGrupos;
    private javax.swing.JButton butonVerUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelNombreUsuarioLogged;
    private javax.swing.JTable tablaVentanaAdministradores;
    // End of variables declaration//GEN-END:variables
}
