/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Byron Garcia
 */
public class VentanaPrincipalDirectores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalDirectores
     */
    public VentanaPrincipalDirectores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Metodos metodo = new Metodos();
    NuevasInsercionesUsuario nuevasInsercionesUsuario = new NuevasInsercionesUsuario();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botnEliminarGrupo = new javax.swing.JButton();
        butonVerUsuarios = new javax.swing.JButton();
        botonEliminarProyecto = new javax.swing.JButton();
        botonVerGrupos = new javax.swing.JButton();
        botonVerAdministradores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentanaPrincipalDirectores = new javax.swing.JTable();
        botonVerProyectos = new javax.swing.JButton();
        botonRegistrarGrupo = new javax.swing.JButton();
        botonVerDirectores = new javax.swing.JButton();
        botonRegistrarProyecto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEditarGrupo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonEditarProyecto = new javax.swing.JButton();
        labelNombreUsuarioLogged = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        botnEliminarGrupo.setBackground(new java.awt.Color(0, 153, 153));
        botnEliminarGrupo.setText("Eliminar Grupo");
        botnEliminarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnEliminarGrupoActionPerformed(evt);
            }
        });

        butonVerUsuarios.setBackground(new java.awt.Color(0, 153, 153));
        butonVerUsuarios.setText("Ver Usuarios");
        butonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonVerUsuariosActionPerformed(evt);
            }
        });

        botonEliminarProyecto.setBackground(new java.awt.Color(0, 153, 153));
        botonEliminarProyecto.setText("Eliminar Proyecto");
        botonEliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProyectoActionPerformed(evt);
            }
        });

        botonVerGrupos.setBackground(new java.awt.Color(0, 153, 153));
        botonVerGrupos.setText("Ver Grupos");
        botonVerGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerGruposActionPerformed(evt);
            }
        });

        botonVerAdministradores.setBackground(new java.awt.Color(0, 153, 153));
        botonVerAdministradores.setText("Ver Administradores");
        botonVerAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerAdministradoresActionPerformed(evt);
            }
        });

        tablaVentanaPrincipalDirectores.setBackground(new java.awt.Color(0, 153, 153));
        tablaVentanaPrincipalDirectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaVentanaPrincipalDirectores.setEnabled(false);
        jScrollPane1.setViewportView(tablaVentanaPrincipalDirectores);

        botonVerProyectos.setBackground(new java.awt.Color(0, 153, 153));
        botonVerProyectos.setText("Ver Proyectos");
        botonVerProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerProyectosActionPerformed(evt);
            }
        });

        botonRegistrarGrupo.setBackground(new java.awt.Color(0, 153, 153));
        botonRegistrarGrupo.setText("Registrar Grupo");
        botonRegistrarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarGrupoActionPerformed(evt);
            }
        });

        botonVerDirectores.setBackground(new java.awt.Color(0, 153, 153));
        botonVerDirectores.setText("Ver Directores");
        botonVerDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDirectoresActionPerformed(evt);
            }
        });

        botonRegistrarProyecto.setBackground(new java.awt.Color(0, 153, 153));
        botonRegistrarProyecto.setText("Registrar Proyecto");
        botonRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarProyectoActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        botonEditarGrupo.setBackground(new java.awt.Color(0, 153, 153));
        botonEditarGrupo.setText("Agregar Usuario a Grupo");
        botonEditarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarGrupoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Ventana de director");

        botonEditarProyecto.setBackground(new java.awt.Color(0, 153, 153));
        botonEditarProyecto.setText("Agregar Avance Proyecto");
        botonEditarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonVerProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonRegistrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(butonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonVerGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botnEliminarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonVerAdministradores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonVerDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonEditarGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(botonEditarProyecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNombreUsuarioLogged, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(labelNombreUsuarioLogged, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonRegistrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonVerProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botnEliminarGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(botonEditarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDirectoresActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaPrincipalDirectores.setModel(metodo.GeneracionTablaDirectores());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerDirectoresActionPerformed

    private void butonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonVerUsuariosActionPerformed
        try {
            this.tablaVentanaPrincipalDirectores.setModel(metodo.GeneracionTablaUsuariosRestringida());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonVerUsuariosActionPerformed

    private void botonVerGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerGruposActionPerformed
        try {
            this.tablaVentanaPrincipalDirectores.setModel(metodo.GeneracionTablaGrupos());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerGruposActionPerformed

    private void botonVerAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerAdministradoresActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaPrincipalDirectores.setModel(metodo.GeneracionTablaAdministradores());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonVerAdministradoresActionPerformed

    private void botonVerProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerProyectosActionPerformed
        // TODO add your handling code here:
        try {
            this.tablaVentanaPrincipalDirectores.setModel(metodo.GeneracionTablaProyectos());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonVerProyectosActionPerformed

    private void botonRegistrarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarGrupoActionPerformed
        // TODO add your handling code here:
        VentanaAgregarGrupo ventanaAgregarGrupo = new VentanaAgregarGrupo(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresDirectores(ventanaAgregarGrupo.comboBoxDirector);
            ventanaAgregarGrupo.setVisible(true);
            ventanaAgregarGrupo.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonRegistrarGrupoActionPerformed

    private void botonRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarProyectoActionPerformed
        // TODO add your handling code here:
        VentanaAgregarProyecto ventanaAgregarProyecto = new VentanaAgregarProyecto(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresGrupos(ventanaAgregarProyecto.comboBoxNombreGrupo);
            ventanaAgregarProyecto.setVisible(true);
            ventanaAgregarProyecto.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonRegistrarProyectoActionPerformed

    private void botonEditarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProyectoActionPerformed
        // TODO add your handling code here:
        VentanaAgregarAvanceProyeco ventanaAgregarAvanceProyecto = new VentanaAgregarAvanceProyeco(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresProyectos(ventanaAgregarAvanceProyecto.comboBoxNombreProyecto);
            ventanaAgregarAvanceProyecto.setVisible(true);
            ventanaAgregarAvanceProyecto.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEditarProyectoActionPerformed

    private void botonEditarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarGrupoActionPerformed
        // TODO add your handling code here:
        VentanaAgregarUsuariosAGrupo ventanaAgregarUsuariosAGrupo = new VentanaAgregarUsuariosAGrupo(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresGrupos(ventanaAgregarUsuariosAGrupo.comboBoxNombresGrupos);
            ventanaAgregarUsuariosAGrupo.setVisible(true);
            ventanaAgregarUsuariosAGrupo.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonEditarGrupoActionPerformed

    private void botnEliminarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnEliminarGrupoActionPerformed
        // TODO add your handling code here:
        VentanaEliminarGrupo ventanaEliminarGrupo = new VentanaEliminarGrupo(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresGrupos(ventanaEliminarGrupo.comboBoxNombreGrupo);
            ventanaEliminarGrupo.setVisible(true);
            ventanaEliminarGrupo.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botnEliminarGrupoActionPerformed

    private void botonEliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProyectoActionPerformed
        // TODO add your handling code here:
        VentanaEliminarProyecto ventanaEliminarProyecto = new VentanaEliminarProyecto(this, true);
        try {
            nuevasInsercionesUsuario.ComboBoxSetValueNombresProyectos(ventanaEliminarProyecto.comboBoxNombreProyecto);
            ventanaEliminarProyecto.setVisible(true);
            ventanaEliminarProyecto.setLocationRelativeTo(this);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEliminarProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalDirectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalDirectores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botnEliminarGrupo;
    private javax.swing.JButton botonEditarGrupo;
    private javax.swing.JButton botonEditarProyecto;
    private javax.swing.JButton botonEliminarProyecto;
    private javax.swing.JButton botonRegistrarGrupo;
    private javax.swing.JButton botonRegistrarProyecto;
    private javax.swing.JButton botonVerAdministradores;
    private javax.swing.JButton botonVerDirectores;
    private javax.swing.JButton botonVerGrupos;
    private javax.swing.JButton botonVerProyectos;
    private javax.swing.JButton butonVerUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelNombreUsuarioLogged;
    private javax.swing.JTable tablaVentanaPrincipalDirectores;
    // End of variables declaration//GEN-END:variables
}
